// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Technical_Test_DHB.DbContext;

namespace Technical_Test_DHB.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20241009013921_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Technical_Test_DHB.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Technical_Test_DHB.Models.Planes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cuota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EdadMaxima")
                        .HasColumnType("int");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<string>("NombrePlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSeguro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoPlan = "A05",
                            Cuota = 675.00m,
                            EdadMaxima = 59,
                            EdadMinima = 18,
                            NombrePlan = "Plan 1",
                            TipoSeguro = "MRE"
                        },
                        new
                        {
                            Id = 2,
                            CodigoPlan = "A04",
                            Cuota = 472.50m,
                            EdadMaxima = 59,
                            EdadMinima = 18,
                            NombrePlan = "Plan 2",
                            TipoSeguro = "MRE"
                        },
                        new
                        {
                            Id = 3,
                            CodigoPlan = "A1B",
                            Cuota = 141.00m,
                            EdadMaxima = 65,
                            EdadMinima = 18,
                            NombrePlan = "Plan A1",
                            TipoSeguro = "MAE"
                        },
                        new
                        {
                            Id = 4,
                            CodigoPlan = "A1C",
                            Cuota = 235.00m,
                            EdadMaxima = 65,
                            EdadMinima = 18,
                            NombrePlan = "Plan A2",
                            TipoSeguro = "MAE"
                        },
                        new
                        {
                            Id = 5,
                            CodigoPlan = "M11",
                            Cuota = 47.00m,
                            EdadMaxima = 30,
                            EdadMinima = 18,
                            NombrePlan = "Plan BA1",
                            TipoSeguro = "MNF"
                        },
                        new
                        {
                            Id = 6,
                            CodigoPlan = "M10",
                            Cuota = 53.00m,
                            EdadMaxima = 30,
                            EdadMinima = 18,
                            NombrePlan = "Plan BA2",
                            TipoSeguro = "MNF"
                        });
                });

            modelBuilder.Entity("Technical_Test_DHB.Models.Seguros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSeguro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroCuentaFinanciera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCuentaFinanciera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSeguro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorCuota")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("Technical_Test_DHB.Models.Seguros", b =>
                {
                    b.HasOne("Technical_Test_DHB.Models.Clientes", "Cliente")
                        .WithMany("Seguros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Technical_Test_DHB.Models.Clientes", b =>
                {
                    b.Navigation("Seguros");
                });
#pragma warning restore 612, 618
        }
    }
}
